// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseConfigStatus, getSupabasePublicEnv } from '@/lib/supabase-config';
import { PREVIEW_LABS, PREVIEW_DOCTORS } from '../../lib/demo-listings';

function createSupabaseClient() {
  const { url, key } = getSupabasePublicEnv();
  const status = getSupabaseConfigStatus();

  if (!url || !key) {
    throw new Error(
      'Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY in Healthsurya/.env.',
    );
  }

  if (!status.configured) {
    throw new Error(status.reason ?? 'Supabase URL is not configured.');
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  });
}

// Client-side mock state attached to window
const getMockDbState = () => {
  if (typeof window === "undefined") {
    return {
      profiles: [],
      bookings: [],
      doctor_appointments: [],
      labs: PREVIEW_LABS,
      lab_tests: [],
      tests: [],
      doctors: PREVIEW_DOCTORS,
      reviews: [],
    };
  }
  const w = window as any;
  if (!w.mockDbState) {
    w.mockDbState = {
      profiles: [
        {
          id: "b1000001-0001-4000-8000-000000000001",
          clerk_user_id: "b1000001-0001-4000-8000-000000000001",
          phone: "9876500505",
          email: "patient@healthsurya.com",
          full_name: "Rahul Sharma",
          role: "patient",
          wallet_balance: 10000,
          verification_status: "approved",
          is_active: true,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }
      ],
      bookings: [
        {
          id: "bk-mock-001",
          patient_id: "b1000001-0001-4000-8000-000000000001",
          lab_id: "b1000001-0001-4000-8000-000000000001",
          test_id: "e1000001-0001-4000-8000-000000000001",
          scheduled_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
          status: "pending",
          home_collection: true,
          address: "123, Civil Lines, Jaunpur",
          notes: "Patient requires morning test.",
          price: 499,
          payment_status: "pending",
          referred_doctor_id: null,
          referred_doctor_name: null,
          prescription_verified: false,
          commission_amount: 0,
          report_url: null,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }
      ],
      doctor_appointments: [],
      labs: PREVIEW_LABS.map(l => ({
        ...l,
        owner_id: "d1000001-0001-4000-8000-000000000001",
        phone: "9876500000",
        email: "preview.lab@healthsurya.com",
        open_time: "07:00",
        close_time: "21:00",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })),
      doctors: PREVIEW_DOCTORS.map(d => ({
        ...d,
        owner_id: "c1000001-0001-4000-8000-000000000001",
        qualification: "MBBS, MD",
        experience_years: d.experience_years ?? 10,
        consultation_fee: d.consultation_fee ?? 500,
        clinic_name: d.clinic_name ?? `${d.full_name} Clinic`,
        clinic_address: d.clinic_address ?? "Civil Lines",
        clinic_phone: "9000000000",
        whatsapp: d.whatsapp ?? "9000000000",
        services: d.services ?? ["Consultation", "Follow-up"],
        open_time: d.open_time ?? "09:00",
        close_time: d.close_time ?? "20:00",
        published: true,
        verified: true,
        profile_views: d.profile_views ?? 120,
        whatsapp_clicks: d.whatsapp_clicks ?? 45,
        total_reviews: d.total_reviews ?? 28,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })),
      lab_tests: PREVIEW_LABS.flatMap(l => ([
        {
          id: `t1-${l.id.slice(3)}`,
          lab_id: l.id,
          test_id: "e1000001-0001-4000-8000-000000000001",
          price: l.minPrice || 299,
          home_collection: true,
          available: true,
          turnaround_hours: 24,
          tests: { name: "Complete Blood Count (CBC)", category: "Pathology" }
        },
        {
          id: `t2-${l.id.slice(3)}`,
          lab_id: l.id,
          test_id: "e1000002-0001-4000-8000-000000000002",
          price: (l.minPrice || 299) + 100,
          home_collection: true,
          available: true,
          turnaround_hours: 24,
          tests: { name: "Thyroid Profile (T3, T4, TSH)", category: "Hormone" }
        }
      ])),
      tests: [
        { id: "e1000001-0001-4000-8000-000000000001", name: "Complete Blood Count (CBC)", category: "Pathology" },
        { id: "e1000002-0001-4000-8000-000000000002", name: "Thyroid Profile (T3, T4, TSH)", category: "Hormone" }
      ],
      reviews: [],
      doctor_gallery: [],
      doctor_reviews: [],
      user_roles: [
        { id: "r1", user_id: "f1000001-0001-4000-8000-000000000001", role: "admin" },
        { id: "r2", user_id: "c1000001-0001-4000-8000-000000000001", role: "doctor" },
        { id: "r3", user_id: "d1000001-0001-4000-8000-000000000001", role: "lab" },
        { id: "r4", user_id: "d1000002-0001-4000-8000-000000000002", role: "pharmacy" },
        { id: "r5", user_id: "b1000001-0001-4000-8000-000000000001", role: "patient" }
      ],
      medicine_orders: [],
      order_tracking_events: []
    };
  }
  return w.mockDbState;
};

// Client-side query filter executor
function executeClientMockQuery(state: any) {
  const db = getMockDbState();
  let list = db[state.tableName] || [];

  // Filter eq
  for (const [col, val] of Object.entries(state.eqFilters)) {
    list = list.filter((item: any) => item[col] === val);
  }

  // Filter or
  if (state.orFilterStr) {
    const filters = state.orFilterStr.split(",");
    list = list.filter((item: any) => {
      return filters.some((f: string) => {
        const match = f.match(/(\w+)\.ilike\.%([^%]+)%/);
        if (match) {
          const col = match[1];
          const query = match[2].toLowerCase();
          return item[col] && String(item[col]).toLowerCase().includes(query);
        }
        return false;
      });
    });
  }

  // Order
  if (state.orderCol) {
    list = [...list].sort((a: any, b: any) => {
      const aVal = a[state.orderCol];
      const bVal = b[state.orderCol];
      if (aVal === bVal) return 0;
      const factor = state.orderAsc ? 1 : -1;
      return aVal > bVal ? factor : -factor;
    });
  }

  // Limit
  if (state.limitVal > 0) {
    list = list.slice(0, state.limitVal);
  }

  // Join logic
  if (state.tableName === "bookings") {
    const getCookie = (name: string) => {
      if (typeof window === "undefined") return null;
      const value = `; ${document.cookie}`;
      const parts = value.split(`; ${name}=`);
      if (parts.length === 2) return parts.pop()?.split(';').shift();
      return null;
    };
    const mockRole = getCookie("mock_role") || "patient";
    const isInternalRole = ["doctor", "lab", "admin", "super_admin"].includes(mockRole);

    list = list.map((b: any) => {
      const lab = db.labs.find((l: any) => l.id === b.lab_id);
      const test = db.tests.find((t: any) => t.id === b.test_id);
      const bookingData = {
        ...b,
        labs: lab ? { name: lab.name, city: lab.city, address: lab.address, image_url: lab.image_url } : null,
        tests: test ? { name: test.name } : null
      };
      
      if (!isInternalRole) {
        delete bookingData.commission_amount;
        delete bookingData.referred_doctor_id;
        delete bookingData.referred_doctor_name;
        delete bookingData.prescription_verified;
      }
      return bookingData;
    });
  } else if (state.tableName === "lab_tests") {
    list = list.map((lt: any) => {
      const test = db.tests.find((t: any) => t.id === lt.test_id);
      return {
        ...lt,
        tests: test ? { name: test.name, category: test.category } : null
      };
    });
  }

  if (state.isSingle) {
    return { data: list[0] || null, error: list[0] ? null : { message: "Row not found" } };
  }
  if (state.isMaybeSingle) {
    return { data: list[0] || null, error: null };
  }

  return { data: list, error: null };
}

function createClientMockQueryBuilder(tableName: string) {
  const state = {
    tableName,
    eqFilters: {} as Record<string, any>,
    orFilterStr: "",
    selectFields: "*",
    isSingle: false,
    isMaybeSingle: false,
    orderCol: "",
    orderAsc: false,
    limitVal: 0,
  };

  const builder = {
    select(fields = "*") {
      state.selectFields = fields;
      return builder;
    },
    eq(col: string, val: any) {
      state.eqFilters[col] = val;
      return builder;
    },
    or(filterStr: string) {
      state.orFilterStr = filterStr;
      return builder;
    },
    order(col: string, opts?: { ascending?: boolean }) {
      state.orderCol = col;
      state.orderAsc = opts?.ascending ?? false;
      return builder;
    },
    limit(val: number) {
      state.limitVal = val;
      return builder;
    },
    single() {
      state.isSingle = true;
      return Promise.resolve(executeClientMockQuery(state));
    },
    maybeSingle() {
      state.isMaybeSingle = true;
      return Promise.resolve(executeClientMockQuery(state));
    },
    insert(payload: any) {
      const items = Array.isArray(payload) ? payload : [payload];
      const inserted: any[] = [];
      const db = getMockDbState();
      for (const item of items) {
        const row = {
          id: item.id || `mock-id-${Math.random().toString(36).substring(2, 11)}`,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          ...item
        };
        db[tableName].push(row);
        inserted.push(row);
      }
      const resVal = Array.isArray(payload) ? inserted : inserted[0];
      return {
        select() {
          return {
            single() {
              return Promise.resolve({ data: resVal, error: null });
            },
            then(onfulfilled: any) {
              return Promise.resolve({ data: inserted, error: null }).then(onfulfilled);
            }
          };
        },
        then(onfulfilled?: (value: any) => any) {
          return Promise.resolve({ data: resVal, error: null }).then(onfulfilled);
        }
      } as any;
    },
    update(payload: any) {
      return {
        eq(col: string, val: any) {
          state.eqFilters[col] = val;
          const db = getMockDbState();
          const list = db[tableName] || [];
          for (const item of list) {
            let match = true;
            for (const [fCol, fVal] of Object.entries(state.eqFilters)) {
              if (item[fCol] !== fVal) match = false;
            }
            if (match) {
              Object.assign(item, payload, { updated_at: new Date().toISOString() });
            }
          }
          return Promise.resolve({ data: {}, error: null });
        }
      };
    },
    delete() {
      return {
        eq(col: string, val: any) {
          state.eqFilters[col] = val;
          const db = getMockDbState();
          const list = db[tableName] || [];
          const remaining = list.filter((item: any) => item[col] !== val);
          db[tableName] = remaining;
          return Promise.resolve({ data: {}, error: null });
        }
      };
    },
    then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
      return Promise.resolve(executeClientMockQuery(state)).then(onfulfilled, onrejected);
    }
  };

  return builder;
}

let _supabase: ReturnType<typeof createSupabaseClient> | null | undefined;

function getSupabaseClient() {
  if (_supabase !== undefined) return _supabase;
  const { url, key } = getSupabasePublicEnv();
  if (!url || !key) {
    _supabase = null;
    return null;
  }
  try {
    _supabase = createSupabaseClient();
  } catch {
    _supabase = null;
  }
  return _supabase;
}

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY === "pk_test_Y2xlcmsubW9jay5kZXYk") {
      if (prop === "from") {
        return (tableName: string) => createClientMockQueryBuilder(tableName);
      }
    }
    const client = getSupabaseClient();
    if (!client) {
      const status = getSupabaseConfigStatus();
      throw new Error(status.reason ?? 'Supabase is not configured.');
    }
    return Reflect.get(client, prop, receiver);
  },
});

export { getSupabaseClient };
